"""AI Engine for NeoSpartan - Google Gemini Integration."""

import json
import random
from typing import List, Dict, Any, Optional, AsyncGenerator
from dataclasses import dataclass
from datetime import datetime

import google.generativeai as genai
from tenacity import retry, stop_after_attempt, wait_exponential

from config import settings


# Configure Gemini
genai.configure(api_key=settings.gemini_api_key)


@dataclass
class AIWorkoutRequest:
    """Request parameters for AI workout generation."""
    user_id: str
    fitness_level: str  # beginner, intermediate, advanced
    training_goal: str
    preferred_duration: int  # minutes
    available_equipment: List[str]
    injuries_or_limitations: List[str]
    recent_performance: Optional[Dict[str, Any]] = None
    preferred_categories: List[str] = None


@dataclass
class AIExercise:
    """Exercise generated by AI."""
    name: str
    category: str
    sets: int
    reps: str  # Can be "MAX" or number
    rpe: float
    rest_seconds: int
    target_metaphor: str
    instructions: str
    primary_muscles: List[str]


@dataclass
class AIWorkoutProtocol:
    """Complete workout protocol from AI."""
    title: str
    subtitle: str
    tier: str
    mindset_prompt: str
    estimated_duration: int
    exercises: List[AIExercise]


class GeminiAIEngine:
    """Google Gemini AI Engine for workout generation."""
    
    SPARTAN_METAPHORS = [
        "Today you forge your shield. Tomorrow you stand the line.",
        "The phalanx is only as strong as its weakest warrior.",
        "Come back with your shield - or on it.",
        "Fear is the enemy. Discipline is your spear.",
        "The Agoge tests not your strength, but your will.",
        "A Spartan never retreats from discomfort.",
        "Your body is bronze. Your mind is iron.",
    ]
    
    STOIC_QUOTES = [
        {"text": "The obstacle is the way.", "author": "Marcus Aurelius"},
        {"text": "You have power over your mind - not outside events.", "author": "Marcus Aurelius"},
        {"text": "Waste no more time arguing what a good man should be. Be one.", "author": "Marcus Aurelius"},
        {"text": "No man is free who is not master of himself.", "author": "Epictetus"},
    ]
    
    def __init__(self):
        self.model = genai.GenerativeModel(
            model_name=settings.gemini_model,
            generation_config={
                "temperature": settings.gemini_temperature,
                "max_output_tokens": settings.gemini_max_tokens,
                "response_mime_type": "application/json",
            }
        )
    
    def _build_workout_prompt(self, request: AIWorkoutRequest) -> str:
        """Build a comprehensive prompt for workout generation."""
        metaphor = random.choice(self.SPARTAN_METAPHORS)
        quote = random.choice(self.STOIC_QUOTES)
        
        performance_context = ""
        if request.recent_performance:
            avg_rpe = request.recent_performance.get('avg_rpe', 0)
            total_volume = request.recent_performance.get('total_volume', 0)
            sessions_count = request.recent_performance.get('sessions_count', 0)
            performance_context = f"""
RECENT PERFORMANCE DATA:
- Average RPE: {avg_rpe}/10
- Total Volume: {total_volume} kg
- Sessions Analyzed: {sessions_count}
Use this data to apply progressive overload where appropriate.
"""
        
        limitations_context = ""
        if request.injuries_or_limitations:
            limitations_context = f"""
INJURIES & LIMITATIONS:
{chr(10).join(f'- {limitation}' for limitation in request.injuries_or_limitations)}
Avoid exercises that stress these areas. Provide safe alternatives.
"""
        
        return f"""You are an elite combat sports conditioning coach in the NeoSpartan system. 
Create a personalized workout for an athlete with the following profile:

ATHLETE PROFILE:
- Fitness Level: {request.fitness_level}
- Training Goal: {request.training_goal}
- Session Duration: {request.preferred_duration} minutes
- Available Equipment: {', '.join(request.available_equipment)}
{limitations_context}
{performance_context}

PHILOSOPHY:
- Metaphor: "{metaphor}"
- Stoic Quote: "{quote['text']}" - {quote['author']}

INSTRUCTIONS:
1. Design a complete workout with 4-8 exercises
2. Match intensity to fitness level and goal
3. Target duration: {request.preferred_duration} minutes
4. Include appropriate warm-up and cool-down time estimates
5. Use Spartan-themed metaphors and motivational language
6. Ensure exercises don't conflict with stated limitations

RESPONSE FORMAT (JSON):
{{
    "title": "Creative Spartan-themed workout name",
    "subtitle": "Brief description of the workout focus",
    "tier": "elite|ready|fatigued|recovery",
    "mindset_prompt": "Motivational message based on Stoic philosophy",
    "estimated_duration": {request.preferred_duration},
    "exercises": [
        {{
            "name": "Exercise name",
            "category": "plyometric|isometric|combat|strength|mobility|sprint",
            "sets": 3,
            "reps": "10 or MAX",
            "rpe": 7.5,
            "rest_seconds": 60,
            "target_metaphor": "Spartan metaphor for this exercise",
            "instructions": "Detailed instructions for proper form",
            "primary_muscles": ["muscle1", "muscle2"]
        }}
    ]
}}

Generate a workout that challenges but respects the athlete's current state."""
    
    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10)
    )
    async def generate_workout(self, request: AIWorkoutRequest) -> AIWorkoutProtocol:
        """Generate a workout using Gemini AI."""
        if not settings.gemini_api_key:
            raise AIEngineError("Gemini API key not configured")
        
        prompt = self._build_workout_prompt(request)
        
        try:
            response = await self.model.generate_content_async(prompt)
            
            if not response.text:
                raise AIEngineError("Empty response from Gemini")
            
            # Parse JSON response
            try:
                data = json.loads(response.text)
            except json.JSONDecodeError as e:
                # Try to extract JSON from markdown code block
                text = response.text
                if "```json" in text:
                    text = text.split("```json")[1].split("```")[0]
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0]
                data = json.loads(text.strip())
            
            # Convert to AIWorkoutProtocol
            exercises = [
                AIExercise(
                    name=ex["name"],
                    category=ex["category"],
                    sets=ex["sets"],
                    reps=str(ex["reps"]),
                    rpe=float(ex["rpe"]),
                    rest_seconds=ex["rest_seconds"],
                    target_metaphor=ex.get("target_metaphor", ""),
                    instructions=ex.get("instructions", ""),
                    primary_muscles=ex.get("primary_muscles", []),
                )
                for ex in data["exercises"]
            ]
            
            return AIWorkoutProtocol(
                title=data["title"],
                subtitle=data["subtitle"],
                tier=data["tier"],
                mindset_prompt=data["mindset_prompt"],
                estimated_duration=data["estimated_duration"],
                exercises=exercises,
            )
            
        except Exception as e:
            raise AIEngineError(f"Failed to generate workout: {e}")
    
    async def generate_workout_stream(
        self, request: AIWorkoutRequest
    ) -> AsyncGenerator[str, None]:
        """Generate a workout with streaming response."""
        if not settings.gemini_api_key:
            raise AIEngineError("Gemini API key not configured")
        
        prompt = self._build_workout_prompt(request)
        
        try:
            response = await self.model.generate_content_async(
                prompt, 
                stream=True
            )
            
            async for chunk in response:
                if chunk.text:
                    yield chunk.text
                    
        except Exception as e:
            raise AIEngineError(f"Streaming generation failed: {e}")
    
    def _build_adaptation_prompt(
        self, 
        current_protocol: Dict[str, Any],
        readiness_score: int,
        joint_stress: Dict[str, int]
    ) -> str:
        """Build prompt for real-time workout adaptation."""
        return f"""Adapt the following workout based on current state:

CURRENT WORKOUT:
{json.dumps(current_protocol, indent=2)}

CURRENT STATE:
- Readiness Score: {readiness_score}/100
- Joint Stress: {json.dumps(joint_stress)}

ADAPTATION RULES:
- If readiness < 50: Switch to recovery mode (reduce volume 50%, lower intensity)
- If joint stress > 7 on any joint: Substitute exercises to reduce that joint's load
- If readiness > 80: Can increase volume 10-20%

Provide adapted workout in the same JSON format."""
    
    async def adapt_workout(
        self,
        current_protocol: Dict[str, Any],
        readiness_score: int,
        joint_stress: Dict[str, int]
    ) -> AIWorkoutProtocol:
        """Adapt a workout in real-time based on current state."""
        prompt = self._build_adaptation_prompt(current_protocol, readiness_score, joint_stress)
        
        try:
            response = await self.model.generate_content_async(prompt)
            
            if not response.text:
                raise AIEngineError("Empty response from Gemini")
            
            data = json.loads(response.text)
            
            exercises = [
                AIExercise(
                    name=ex["name"],
                    category=ex["category"],
                    sets=ex["sets"],
                    reps=str(ex["reps"]),
                    rpe=float(ex["rpe"]),
                    rest_seconds=ex["rest_seconds"],
                    target_metaphor=ex.get("target_metaphor", ""),
                    instructions=ex.get("instructions", ""),
                    primary_muscles=ex.get("primary_muscles", []),
                )
                for ex in data["exercises"]
            ]
            
            return AIWorkoutProtocol(
                title=data["title"],
                subtitle=data["subtitle"],
                tier=data["tier"],
                mindset_prompt=data["mindset_prompt"],
                estimated_duration=data["estimated_duration"],
                exercises=exercises,
            )
            
        except Exception as e:
            raise AIEngineError(f"Failed to adapt workout: {e}")


class AIEngineError(Exception):
    """Custom exception for AI engine errors."""
    pass


# ============== DOM-RL Fallback ==============

class DOMRLEngine:
    """Rule-based fallback engine when AI is unavailable."""
    
    def calculate_readiness(self, micro_cycle_data: List[Dict]) -> Dict[str, Any]:
        """Calculate readiness score from micro-cycle data."""
        if not micro_cycle_data:
            return {
                "score": 75,
                "volume": 0.0,
                "fatigue": {},
                "trend": "stable"
            }
        
        # Calculate average RPE
        rpes = [day.get("readiness_score", 75) for day in micro_cycle_data]
        avg_rpe = sum(rpes) / len(rpes)
        
        # Calculate volume
        volume = sum(
            len(day.get("rpe_entries", [])) * sum(day.get("rpe_entries", [])) / max(len(day.get("rpe_entries", [])), 1)
            for day in micro_cycle_data
        )
        
        # Check fatigue
        joint_fatigue = {}
        for day in micro_cycle_data:
            for joint, fatigue in day.get("joint_fatigue", {}).items():
                if joint not in joint_fatigue:
                    joint_fatigue[joint] = []
                joint_fatigue[joint].append(fatigue)
        
        fatigue = {
            joint: sum(values) / len(values) * (1 + len(values) * 0.1)
            for joint, values in joint_fatigue.items()
        }
        
        # Determine trend
        trend = "stable"
        if len(rpes) >= 2:
            if rpes[-1] > rpes[0] * 1.1:
                trend = "improving"
            elif rpes[-1] < rpes[0] * 0.9:
                trend = "declining"
        
        return {
            "score": int(avg_rpe),
            "volume": volume,
            "fatigue": fatigue,
            "trend": trend
        }
    
    def generate_action(self, readiness: int) -> Dict[str, Any]:
        """Generate action based on readiness."""
        if readiness >= 85:
            return {
                "volume_adjustment": 0.2,
                "intensity_adjustment": 0.15,
                "rest_adjustment": -10,
                "focus_area": "power"
            }
        elif readiness >= 65:
            return {
                "volume_adjustment": 0.0,
                "intensity_adjustment": 0.05,
                "rest_adjustment": 0,
                "focus_area": "balanced"
            }
        elif readiness >= 45:
            return {
                "volume_adjustment": -0.2,
                "intensity_adjustment": -0.1,
                "rest_adjustment": 15,
                "focus_area": "endurance"
            }
        else:
            return {
                "volume_adjustment": -0.5,
                "intensity_adjustment": -0.4,
                "rest_adjustment": 30,
                "focus_area": "recovery"
            }


# Global instances
gemini_engine = GeminiAIEngine()
dom_rl_engine = DOMRLEngine()
