import 'dart:async';
import 'dart:developer' as developer;
import '../services/hybrid_storage_service.dart';
import '../models/ai_memory.dart';

/// Service for managing AI memories using Hybrid Storage
class AIMemoryService {
  static final AIMemoryService _instance = AIMemoryService._internal();
  factory AIMemoryService() => _instance;
  AIMemoryService._internal();

  final HybridStorageService _storage = HybridStorageService();

  /// Store a new memory (convenience method)
  Future<bool> storeMemory({
    required String userId,
    required AIMemoryType type,
    required MemoryPriority priority,
    required Map<String, dynamic> data,
    required List<String> tags,
    String summary = '',
    DateTime? expiresAt,
  }) async {
    try {
      final memory = AIMemoryEntry(
        id: '', // Will be generated by database
        userId: userId,
        type: type,
        priority: priority,
        data: data,
        tags: tags,
        summary: summary,
        createdAt: DateTime.now(),
        expiresAt: expiresAt ?? DateTime.now().add(const Duration(days: 30)),
        lastAccessed: DateTime.now(),
        accessCount: 0,
      );

      final success = await _storage.storeMemory({
        'type': memory.type.toString(),
        'priority': memory.priority.toString(),
        'data': memory.data,
        'tags': memory.tags,
        'summary': memory.summary,
        'expires_at': memory.expiresAt.toIso8601String(),
      });

      developer.log('AI memory stored successfully', name: 'AIMemoryService');
      return success;
    } catch (e) {
      developer.log('Error storing AI memory: $e', name: 'AIMemoryService');
      return false;
    }
  }

  /// Store a new memory (direct method)
  Future<bool> storeMemoryEntry(AIMemoryEntry memory) async {
    try {
      final success = await _storage.storeMemory({
        'type': memory.type.toString(),
        'priority': memory.priority.toString(),
        'data': memory.data,
        'tags': memory.tags,
        'summary': memory.summary,
        'expires_at': memory.expiresAt.toIso8601String(),
      });

      developer.log('AI memory stored successfully', name: 'AIMemoryService');
      return success;
    } catch (e) {
      developer.log('Error storing AI memory: $e', name: 'AIMemoryService');
      return false;
    }
  }

  /// Query memories by type
  Future<List<AIMemoryEntry>> queryMemories({
    AIMemoryType? type,
    int limit = 50,
  }) async {
    try {
      final response = await _storage.queryMemories(
        type: type?.toString(),
        limit: limit,
      );

      return response
          .map(
            (data) => AIMemoryEntry(
              id: data['id'],
              userId: data['userId'] ?? '',
              type: _parseMemoryType(data['type']),
              priority: _parseMemoryPriority(data['priority']),
              data: data['data'] ?? {},
              tags: List<String>.from(data['tags'] ?? []),
              summary: data['summary'] ?? '',
              createdAt: DateTime.parse(data['createdAt']),
              expiresAt: data['expires_at'] != null
                  ? DateTime.parse(data['expires_at'])
                  : DateTime.now(),
              lastAccessed: data['last_accessed'] != null
                  ? DateTime.parse(data['last_accessed'])
                  : DateTime.now(),
              accessCount: data['access_count'] ?? 0,
            ),
          )
          .toList();
    } catch (e) {
      developer.log('Error querying AI memories: $e', name: 'AIMemoryService');
      return [];
    }
  }

  /// Get memory by ID
  Future<AIMemoryEntry?> getMemoryById(String memoryId) async {
    try {
      // For now, query all memories and filter by ID
      // In a real implementation, you'd add a getById method to HybridStorageService
      final memories = await queryMemories(limit: 1000);
      return memories.firstWhere(
        (memory) => memory.id == memoryId,
        orElse: () => AIMemoryEntry(
          id: '',
          userId: '',
          type: AIMemoryType.workoutHistory,
          priority: MemoryPriority.low,
          data: {},
          tags: [],
          summary: '',
          createdAt: DateTime.now(),
          expiresAt: DateTime.now(),
          lastAccessed: DateTime.now(),
          accessCount: 0,
        ),
      );
    } catch (e) {
      developer.log('Error getting AI memory: $e', name: 'AIMemoryService');
      return null;
    }
  }

  /// Get memory statistics
  Future<Map<String, dynamic>> getMemoryStats(String userId) async {
    try {
      // This would typically be a database query
      // For now, return placeholder stats
      return {'totalMemories': 0, 'byType': {}, 'byPriority': {}};
    } catch (e) {
      developer.log('Error getting memory stats: $e', name: 'AIMemoryService');
      return {};
    }
  }

  /// Record memory access
  Future<void> recordAccess(String userId, String memoryId) async {
    try {
      // This would update the access count and timestamp
      // Implementation depends on your database structure
    } catch (e) {
      developer.log(
        'Error recording memory access: $e',
        name: 'AIMemoryService',
      );
    }
  }

  /// Delete expired memories
  Future<int> cleanupExpiredMemories(String userId) async {
    try {
      // This would typically be done via a database trigger or scheduled job
      // For now, we'll fetch expired memories and delete them

      final memories = await queryMemories(limit: 1000);
      final now = DateTime.now();

      int deletedCount = 0;
      for (final memory in memories) {
        if (memory.expiresAt.isBefore(now)) {
          // In a real implementation, you'd delete the memory
          // For now, just count expired memories
          deletedCount++;
        }
      }

      developer.log(
        'Found $deletedCount expired memories',
        name: 'AIMemoryService',
      );
      return deletedCount;
    } catch (e) {
      developer.log(
        'Error cleaning up expired memories: $e',
        name: 'AIMemoryService',
      );
      return 0;
    }
  }

  /// Search memories by text
  Future<List<AIMemoryEntry>> searchMemories(
    String query, {
    int limit = 20,
  }) async {
    try {
      // In a real implementation, you'd use PostgreSQL full-text search
      // For now, we'll fetch all memories and filter
      final memories = await queryMemories(limit: 100);

      final results = memories
          .where((memory) {
            return (memory.summary?.toLowerCase().contains(
                      query.toLowerCase(),
                    ) ??
                    false) ||
                (memory.tags?.any(
                      (tag) => tag.toLowerCase().contains(query.toLowerCase()),
                    ) ??
                    false);
          })
          .take(limit)
          .toList();

      return results;
    } catch (e) {
      developer.log('Error searching AI memories: $e', name: 'AIMemoryService');
      return [];
    }
  }

  /// Parse memory type from string
  AIMemoryType _parseMemoryType(String? typeString) {
    if (typeString == null) return AIMemoryType.workoutHistory;

    for (final type in AIMemoryType.values) {
      if (type.toString() == typeString) return type;
    }
    return AIMemoryType.workoutHistory;
  }

  /// Parse memory priority from string
  MemoryPriority _parseMemoryPriority(String? priorityString) {
    if (priorityString == null) return MemoryPriority.medium;

    for (final priority in MemoryPriority.values) {
      if (priority.toString() == priorityString) return priority;
    }
    return MemoryPriority.medium;
  }
}
